name: sanex tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sanex
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: sanex
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: sanecmp/sanelib
          ref: main
          path: sanelib
      - uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      - run: uv sync --group tests --python ${{ matrix.python-version }}
      - run: uv run --no-sync pytest
